# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManagerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 808)
        palette = QtGui.QPalette()
        palette.setBrush(MainWindow.backgroundRole(),QtGui.QBrush(QtGui.QImage("./resource/imgback/back.jpg").scaled(MainWindow.size())))
        MainWindow.setPalette(palette)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1366, 811))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(70, 540, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(60, 590, 591, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(680, 590, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        #self.label_5 = QtWidgets.QLabel(self.tab)
        #self.label_5.setGeometry(QtCore.QRect(680, 630, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        #self.label_5.setFont(font)
        #self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(680, 666, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_selectid = QtWidgets.QPushButton(self.tab)
        self.pushButton_selectid.setGeometry(QtCore.QRect(1250, 590, 80, 22))
        self.pushButton_selectid.setObjectName("pushButton_selectid")
        #self.pushButton_selecttest = QtWidgets.QPushButton(self.tab)
        #self.pushButton_selecttest.setGeometry(QtCore.QRect(1250, 630, 80, 22))
        #self.pushButton_selecttest.setObjectName("pushButton_selecttest")
        self.pushButton_selectmodel = QtWidgets.QPushButton(self.tab)
        self.pushButton_selectmodel.setGeometry(QtCore.QRect(1250, 670, 80, 22))
        self.pushButton_selectmodel.setObjectName("pushButton_selectmodel")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(940, 80, 381, 391))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_renamefloder = QtWidgets.QPushButton(self.frame)
        self.pushButton_renamefloder.setGeometry(QtCore.QRect(20, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_renamefloder.setFont(font)
        self.pushButton_renamefloder.setObjectName("pushButton_renamefloder")
        self.pushButton_resizeimage = QtWidgets.QPushButton(self.frame)
        self.pushButton_resizeimage.setGeometry(QtCore.QRect(250, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_resizeimage.setFont(font)
        self.pushButton_resizeimage.setObjectName("pushButton_resizeimage")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(30, 300, 331, 41))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_loadmodel = QtWidgets.QPushButton(self.frame)
        self.pushButton_loadmodel.setGeometry(QtCore.QRect(140, 150, 121, 41))
        self.pushButton_loadmodel.setObjectName("pushButton_loadmodel")
        self.label_idfolder = QtWidgets.QLabel(self.tab)
        self.label_idfolder.setGeometry(QtCore.QRect(790, 590, 420, 22))
        self.label_idfolder.setText("/opt/disk/gouwenbo/por/id")
        self.label_idfolder.setObjectName("label_idfolder")
        #self.label_testfolder = QtWidgets.QLabel(self.tab)
        #self.label_testfolder.setGeometry(QtCore.QRect(790, 640, 420, 22))
        #self.label_testfolder.setText("")
        #self.label_testfolder.setObjectName("label_testfolder")
        self.label_modelfolder = QtWidgets.QLabel(self.tab)
        self.label_modelfolder.setGeometry(QtCore.QRect(790, 670, 420, 22))
        self.label_modelfolder.setText("/opt/disk/gouwenbo/por/models/model-r34-amf")
        self.label_modelfolder.setObjectName("label_modelfolder")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber.setGeometry(QtCore.QRect(1210, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setDigitCount(6)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 60.0)
        self.lcdNumber.setProperty("intValue", 60)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(1100, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(60, 80, 761, 391))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(160, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(19, 50, 971, 621))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_video = QtWidgets.QLabel(self.frame_2)
        self.label_video.setGeometry(QtCore.QRect(18, 10, 941, 601))
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.label_video.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(1040, 50, 301, 621))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(10, 170, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.checkBox_fps = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_fps.setGeometry(QtCore.QRect(170, 230, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_fps.setFont(font)
        self.checkBox_fps.setObjectName("checkBox_fps")
        self.checkBox_box = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_box.setGeometry(QtCore.QRect(30, 230, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_box.setFont(font)
        self.checkBox_box.setObjectName("checkBox_box")
        self.checkBox_id = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_id.setGeometry(QtCore.QRect(30, 290, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_id.setFont(font)
        self.checkBox_id.setObjectName("checkBox_id")
        self.checkBox_landmarls = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_landmarls.setGeometry(QtCore.QRect(170, 290, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_landmarls.setFont(font)
        self.checkBox_landmarls.setObjectName("checkBox_landmarls")
        self.checkBox_distance = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_distance.setGeometry(QtCore.QRect(90, 340, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_distance.setFont(font)
        self.checkBox_distance.setObjectName("checkBox_distance")
        self.pushButton_opencam = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_opencam.setGeometry(QtCore.QRect(21, 570, 101, 41))
        self.pushButton_opencam.setObjectName("pushButton_opencam")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(11, 390, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(100, 410, 101, 21))
        self.label_13.setObjectName("label_13")
        self.pushButton_closecam = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_closecam.setGeometry(QtCore.QRect(170, 570, 101, 41))
        self.pushButton_closecam.setObjectName("pushButton_closecamFchan")
        self.radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton.setGeometry(QtCore.QRect(20, 450, 51, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_2.setGeometry(QtCore.QRect(100, 450, 41, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_3.setGeometry(QtCore.QRect(170, 450, 51, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_4.setGeometry(QtCore.QRect(240, 450, 41, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(100, 480, 91, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(10, 520, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(30, 50, 61, 21))
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(30, 90, 61, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(30, 133, 81, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(120, 50, 111, 25))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(120, 90, 111, 25))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(120, 130, 111, 25))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.action_gpu = QtWidgets.QAction(MainWindow)
        self.action_gpu.setObjectName("action_gpu")
        self.action_camera = QtWidgets.QAction(MainWindow)
        self.action_camera.setObjectName("action_camera")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "管理界面"))
        self.label.setText(_translate("MainWindow", "操作反馈"))
        self.label_4.setText(_translate("MainWindow", "ID目录"))
        #self.label_5.setText(_translate("MainWindow", "测试目录"))
        self.label_6.setText(_translate("MainWindow", "模型目录"))
        self.pushButton_selectid.setText(_translate("MainWindow", "选择目录"))
        #self.pushButton_selecttest.setText(_translate("MainWindow", "选择目录"))
        self.pushButton_selectmodel.setText(_translate("MainWindow", "选择目录"))
        self.label_7.setText(_translate("MainWindow", "功能选区"))
        self.pushButton_renamefloder.setText(_translate("MainWindow", "Rename目录"))
        self.pushButton_resizeimage.setText(_translate("MainWindow", "Resize图像"))
        self.label_8.setText(_translate("MainWindow", "处理进度"))
        self.pushButton_loadmodel.setText(_translate("MainWindow", "载入ID与模型"))
        self.label_19.setText(_translate("MainWindow", "总人数："))
        self.pushButton_6.setText(_translate("MainWindow", "增量ID"))
        self.pushButton_4.setText(_translate("MainWindow", "人员管理"))
        self.pushButton_5.setText(_translate("MainWindow", "部门管理"))
        self.pushButton_7.setText(_translate("MainWindow", "考勤查询"))
        self.label_20.setText(_translate("MainWindow", "操作选区"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "功能界面"))
        self.label_9.setText(_translate("MainWindow", "视频画面"))
        self.label_10.setText(_translate("MainWindow", "功能选区"))
        self.checkBox_fps.setText(_translate("MainWindow", "显示FPS"))
        self.checkBox_box.setText(_translate("MainWindow", "显示BOX"))
        self.checkBox_id.setText(_translate("MainWindow", "显示ID"))
        self.checkBox_landmarls.setText(_translate("MainWindow", "显示特征点"))
        self.checkBox_distance.setText(_translate("MainWindow", "显示Distance"))
        self.pushButton_opencam.setText(_translate("MainWindow", "打开视频流"))
        self.label_11.setText(_translate("MainWindow", "设置选区"))
        self.label_13.setText(_translate("MainWindow", "Camera编号"))
        self.pushButton_closecam.setText(_translate("MainWindow", "关闭视频流"))
        self.radioButton.setText(_translate("MainWindow", "0"))
        self.radioButton_2.setText(_translate("MainWindow", "1"))
        self.radioButton_3.setText(_translate("MainWindow", "2"))
        self.radioButton_4.setText(_translate("MainWindow", "3"))
        self.label_2.setText(_translate("MainWindow", "推流地址"))
        self.label_3.setText(_translate("MainWindow", "识别结果"))
        self.label_12.setText(_translate("MainWindow", "识别ID："))
        self.label_14.setText(_translate("MainWindow", "置信度："))
        self.label_15.setText(_translate("MainWindow", "考勤结果："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "监控界面"))
        self.action_gpu.setText(_translate("MainWindow", "显卡设备"))
        self.action_camera.setText(_translate("MainWindow", "Camera设置"))
        self.action_6.setText(_translate("MainWindow", "关于"))

